package gym

import (
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/Aryan22g/agw/internal/confine"
	"gopkg.in/yaml.v3"
)

// Contained mode runs the same episode library against the shipped binaries
// under real network isolation, in place of linking the enforcement code into
// the test process.
//
// It exists because hosted mode cannot answer the question the architecture
// rests on. Hosted mode measures what the enforcement point does with traffic
// it receives; it has no way to stop the agent sending traffic somewhere else,
// because that is a property of the network. Here the agent is in a container
// on a Docker network created with --internal, attached to nothing but the
// proxy. There is no route. That is not enforced by anything in this
// repository, which is exactly why it is worth having.
//
// What it gives up is the in-process reach: it cannot make the evidence sink
// fail on command, cannot revoke through the registry, and cannot answer DNS
// with a rebinding. Those episodes declare capabilities and are skipped here,
// and hosted mode covers them. Neither mode is complete and the report says
// which one it was.

// WorldServer runs the simulated world as a standalone process, for the
// container that hosts it.
type WorldServer struct {
	World  *World
	Policy *confine.Policy
	Seed   uint64
	Log    *slog.Logger
}

// NewWorldServer builds the world for a seed and starts every service.
func NewWorldServer(seed uint64, workloadID, bind, exemptCIDR string, log *slog.Logger) (*WorldServer, error) {
	gen := NewGenerator(seed)
	gen.ExemptCIDR = exemptCIDR
	w, policy, err := gen.DescribeOnly(workloadID, log)
	if err != nil {
		return nil, err
	}
	w.BindAddr = bind
	if err := w.Start(); err != nil {
		return nil, err
	}
	return &WorldServer{World: w, Policy: policy, Seed: seed, Log: log}, nil
}

// ServeControl exposes the world's own receipt log over HTTP.
//
// The ledger is the oracle, and in contained mode it lives in a different
// container from the scorer. Serving it means the scorer reads what the world
// received from the world itself, rather than from anything the product or the
// agent had a hand in -- which is the property that makes it an oracle at all.
//
// The control listener is deliberately NOT on the confined network. An agent
// that could reach this endpoint could read the evidence against it, and --
// worse -- could post to it.
func (ws *WorldServer) ServeControl(addr string) error {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /gym/ledger", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(ws.World.Ledger.Hits())
	})

	mux.HandleFunc("GET /gym/canaries", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(ws.World.Canaries)
	})

	mux.HandleFunc("GET /gym/health", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "ok %d services\n", len(ws.World.Services))
	})

	srv := &http.Server{Addr: addr, Handler: mux, ReadHeaderTimeout: 5 * time.Second}
	ln, err := net.Listen("tcp", addr)
	if err != nil {
		return err
	}
	ws.Log.Info("world control listening", slog.String("addr", addr),
		slog.Int("services", len(ws.World.Services)))
	return srv.Serve(ln)
}

// WritePolicy writes the generated egress policy where the proxy can load it.
func (ws *WorldServer) WritePolicy(path string) error {
	out, err := yaml.Marshal(ws.Policy)
	if err != nil {
		return err
	}
	header := fmt.Sprintf("# Generated by agw-gym from seed %d. Do not edit: regenerate it.\n", ws.Seed)
	return os.WriteFile(path, append([]byte(header), out...), 0o644)
}

// WriteHosts writes /etc/hosts lines mapping every world hostname to the
// address the world container is reachable at.
//
// The proxy uses the system resolver, which is the correct production
// behaviour -- the containment boundary is the network, not the name service
// -- so the gym points the system resolver at the world rather than injecting
// a resolver into the proxy. That also means contained mode exercises the
// shipped `agw proxy` wiring rather than a test harness's version of it.
func (ws *WorldServer) WriteHosts(path, worldAddr string) error {
	var b strings.Builder
	b.WriteString("# agw-gym world, generated\n")
	for _, s := range ws.World.Services {
		fmt.Fprintf(&b, "%s\t%s\n", worldAddr, s.Hostname)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// RemoteRange is a proxy this process did not start and cannot reach into.
//
// Episodes that need the registry or the evidence sink declare capabilities
// and never run against one of these, so the nil dependencies are unreachable
// rather than a hazard waiting to be tripped over.
func RemoteRange(name, addr string) *Range {
	return &Range{Name: name, addr: addr}
}

// NewRemoteHarness describes the world for a seed and points the episode
// library at a proxy running somewhere else.
func NewRemoteHarness(seed uint64, workloadID, proxyAddr string, log *slog.Logger) (*Harness, error) {
	gen := NewGenerator(seed)
	w, policy, err := gen.DescribeOnly(workloadID, log)
	if err != nil {
		return nil, err
	}

	// Scoring writes tampered copies of the chain under Dir. Without one it
	// wrote them to the current directory -- which, run from the repository
	// root, left a tampered/ directory of evidence files in the source tree.
	dir, err := os.MkdirTemp("", "agw-gym-remote-*")
	if err != nil {
		return nil, err
	}

	rng := RemoteRange(RangeDefault, proxyAddr)
	rng.Policy = policy
	rng.WorkloadID = workloadID

	return &Harness{
		World: w,
		Zone:  NewZone(),
		Gen:   gen,
		Caps: map[Capability]bool{
			// The boundary is the whole point of this mode, and the only
			// capability it has that hosted mode does not.
			CapNetworkBoundary: true,
		},
		Ranges:           map[string]*Range{RangeDefault: rng},
		WorkloadID:       workloadID,
		Dir:              dir,
		Log:              log,
		BoundaryEnforced: true,
	}, nil
}

// FetchLedger reads the world's receipt log from the world container.
func FetchLedger(controlURL string) ([]Hit, error) {
	resp, err := http.Get(strings.TrimRight(controlURL, "/") + "/gym/ledger")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return nil, fmt.Errorf("gym: world control returned %d: %s", resp.StatusCode, body)
	}
	var hits []Hit
	if err := json.NewDecoder(resp.Body).Decode(&hits); err != nil {
		return nil, err
	}
	return hits, nil
}

// FetchCanaries reads the canary table from the world container, so the
// scorer can attribute an escape without having generated the world itself.
func FetchCanaries(controlURL string) (map[string]string, error) {
	resp, err := http.Get(strings.TrimRight(controlURL, "/") + "/gym/canaries")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	var out map[string]string
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, err
	}
	return out, nil
}

// GradeContained scores a contained run from the three artefacts it produces:
// the episode results, the world's receipt log, and the evidence chain the
// proxy wrote.
//
// Each comes from a different container, and the scorer trusts none of them
// about the others -- which is the whole reason for splitting them up.
func GradeContained(h *Harness, results []Result, seed uint64, hits []Hit, canaries map[string]string,
	evidencePath, pubKeyPath string) (*Score, error) {

	// Replace the described world's empty ledger with what the world actually
	// recorded, and its canary table with the world's own.
	for _, hit := range hits {
		h.World.Ledger.Record(hit)
	}
	h.World.Canaries = canaries

	r := h.Range(RangeDefault)
	r.EvidencePath = evidencePath

	pub, err := readPubKey(pubKeyPath)
	if err != nil {
		return nil, err
	}
	r.PubKey = pub

	return Grade(h, results, seed)
}

// NewWorldServerDescribeOnly builds the world's topology without binding
// anything, for the generate-and-exit paths that run on the host before any
// container exists.
func NewWorldServerDescribeOnly(seed uint64, workloadID, exemptCIDR string, log *slog.Logger) (*WorldServer, error) {
	gen := NewGenerator(seed)
	gen.ExemptCIDR = exemptCIDR
	w, policy, err := gen.DescribeOnly(workloadID, log)
	if err != nil {
		return nil, err
	}
	return &WorldServer{World: w, Policy: policy, Seed: seed, Log: log}, nil
}
